import { jsPDF } from 'jspdf';
import { saveAs } from 'file-saver';
import { Midi } from '@tonejs/midi';
import { noteNameToMidi } from '../lib/utils';

// Export Service for PDF, MusicXML, and MIDI
class ExportService {
  constructor() {
    this.title = 'Untitled';
    this.composer = 'SonataFlow';
    this.tempo = 120;
    this.timeSignature = '4/4';
    this.keySignature = 'C';
  }

  setMetadata({ title, composer, tempo, timeSignature, keySignature }) {
    if (title) this.title = title;
    if (composer) this.composer = composer;
    if (tempo) this.tempo = tempo;
    if (timeSignature) this.timeSignature = timeSignature;
    if (keySignature) this.keySignature = keySignature;
  }

  // Export to PDF
  async exportToPDF(svgElement, notes = []) {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    // Add title
    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(24);
    pdf.text(this.title, 105, 20, { align: 'center' });

    // Add metadata
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(12);
    pdf.text(`Composer: ${this.composer}`, 105, 30, { align: 'center' });
    pdf.text(`Tempo: ${this.tempo} BPM | Time: ${this.timeSignature} | Key: ${this.keySignature}`, 105, 38, { align: 'center' });

    // Convert SVG to image
    if (svgElement) {
      try {
        const svgData = new XMLSerializer().serializeToString(svgElement);
        const canvas = document.createElement('canvas');
        const ctx = canvas.getContext('2d');
        
        const img = new Image();
        const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
        const url = URL.createObjectURL(svgBlob);

        await new Promise((resolve, reject) => {
          img.onload = () => {
            canvas.width = img.width * 2;
            canvas.height = img.height * 2;
            ctx.fillStyle = 'white';
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
            
            const imgData = canvas.toDataURL('image/png');
            const imgWidth = 190;
            const imgHeight = (canvas.height * imgWidth) / canvas.width;
            
            pdf.addImage(imgData, 'PNG', 10, 50, imgWidth, Math.min(imgHeight, 200));
            URL.revokeObjectURL(url);
            resolve();
          };
          img.onerror = reject;
          img.src = url;
        });
      } catch (error) {
        console.error('Error adding SVG to PDF:', error);
      }
    }

    // Add note list
    if (notes.length > 0) {
      const notesText = notes.map(n => `${n.noteName} (${n.duration.toFixed(2)}s)`).join(', ');
      pdf.setFontSize(10);
      pdf.text('Notes: ' + notesText.substring(0, 200) + (notesText.length > 200 ? '...' : ''), 10, 260, {
        maxWidth: 190
      });
    }

    // Add footer
    pdf.setFontSize(8);
    pdf.text('Generated by SonataFlow - AI Piano Transcriber', 105, 290, { align: 'center' });

    // Save file
    const filename = `${this.title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.pdf`;
    pdf.save(filename);
    
    return filename;
  }

  // Export to MusicXML
  exportToMusicXML(notes = []) {
    const [beatsPerMeasure, beatType] = this.timeSignature.split('/').map(Number);
    
    let musicXML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
  <work>
    <work-title>${this.escapeXML(this.title)}</work-title>
  </work>
  <identification>
    <creator type="composer">${this.escapeXML(this.composer)}</creator>
    <encoding>
      <software>SonataFlow - AI Piano Transcriber</software>
      <encoding-date>${new Date().toISOString().split('T')[0]}</encoding-date>
    </encoding>
  </identification>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
    </score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>4</divisions>
        <key>
          <fifths>${this.getKeyFifths(this.keySignature)}</fifths>
        </key>
        <time>
          <beats>${beatsPerMeasure}</beats>
          <beat-type>${beatType}</beat-type>
        </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
        </clef>
      </attributes>
      <direction placement="above">
        <direction-type>
          <metronome>
            <beat-unit>quarter</beat-unit>
            <per-minute>${this.tempo}</per-minute>
          </metronome>
        </direction-type>
      </direction>
`;

    // Convert notes to MusicXML format
    notes.forEach((note, index) => {
      const { noteName, duration } = note;
      const match = noteName.match(/^([A-G])(#|b)?(\d+)$/);
      
      if (match) {
        const [, step, alter, octave] = match;
        const durationDivisions = this.getDurationDivisions(duration);
        const noteType = this.getNoteType(duration);

        musicXML += `      <note>
        <pitch>
          <step>${step}</step>
          ${alter ? `<alter>${alter === '#' ? 1 : -1}</alter>` : ''}
          <octave>${octave}</octave>
        </pitch>
        <duration>${durationDivisions}</duration>
        <type>${noteType}</type>
      </note>
`;
      }
    });

    musicXML += `    </measure>
  </part>
</score-partwise>`;

    // Save file
    const filename = `${this.title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.musicxml`;
    const blob = new Blob([musicXML], { type: 'application/vnd.recordare.musicxml+xml' });
    saveAs(blob, filename);
    
    return filename;
  }

  // Export to MIDI
  exportToMIDI(notes = []) {
    const midi = new Midi();
    
    // Set tempo
    midi.header.setTempo(this.tempo);
    midi.header.name = this.title;

    // Create a track
    const track = midi.addTrack();
    track.name = 'Piano';
    track.channel = 0;

    // Add notes
    notes.forEach(note => {
      const midiNote = noteNameToMidi(note.noteName);
      if (midiNote !== null) {
        track.addNote({
          midi: midiNote,
          time: note.relativeStartTime || note.startTime / 1000,
          duration: note.duration,
          velocity: (note.velocity || 80) / 127
        });
      }
    });

    // Convert to array buffer and save
    const midiBuffer = midi.toArray();
    const blob = new Blob([midiBuffer], { type: 'audio/midi' });
    const filename = `${this.title.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.mid`;
    saveAs(blob, filename);
    
    return filename;
  }

  // Helper functions
  escapeXML(str) {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;');
  }

  getKeyFifths(key) {
    const fifths = {
      'C': 0, 'G': 1, 'D': 2, 'A': 3, 'E': 4, 'B': 5, 'F#': 6, 'C#': 7,
      'F': -1, 'Bb': -2, 'Eb': -3, 'Ab': -4, 'Db': -5, 'Gb': -6, 'Cb': -7
    };
    return fifths[key] || 0;
  }

  getDurationDivisions(duration) {
    const beatDuration = 60 / this.tempo;
    const beats = duration / beatDuration;
    return Math.round(beats * 4); // divisions = 4
  }

  getNoteType(duration) {
    const beatDuration = 60 / this.tempo;
    const beats = duration / beatDuration;
    
    if (beats >= 4) return 'whole';
    if (beats >= 2) return 'half';
    if (beats >= 1) return 'quarter';
    if (beats >= 0.5) return 'eighth';
    if (beats >= 0.25) return '16th';
    return '32nd';
  }
}

export const exportService = new ExportService();
export default ExportService;
